package dev.filinhat.bikecalc.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xfffdae02)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xfff6bb3c)
val md_theme_light_onPrimaryContainer = Color(0xFF231B00)
val md_theme_light_secondary = Color(0xFF005CBC)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD7E2FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001B3F)
val md_theme_light_tertiary = Color(0xFF006E1D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF93FA90)
val md_theme_light_onTertiaryContainer = Color(0xFF002204)
val md_theme_light_error = Color(0xFFB22930)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD7)
val md_theme_light_onErrorContainer = Color(0xFF410005)
val md_theme_light_outline = Color(0xFF71787E)
val md_theme_light_background = Color(0xffffefc2)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inversePrimary = Color(0xffe19f37)
val md_theme_light_surfaceTint = Color(0xFFF6F6F6)
val md_theme_light_outlineVariant = Color(0xFFC0C7CD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFE7C349)
val md_theme_dark_onPrimary = Color(0xFF3A300B)
val md_theme_dark_primaryContainer = Color(0xFFFFE081)
val md_theme_dark_onPrimaryContainer = Color(0xFF231B00)
val md_theme_dark_secondary = Color(0xFFABC7FF)
val md_theme_dark_onSecondary = Color(0xFF002F66)
val md_theme_dark_secondaryContainer = Color(0xFF004590)
val md_theme_dark_onSecondaryContainer = Color(0xFFD7E2FF)
val md_theme_dark_tertiary = Color(0xFF77DC77)
val md_theme_dark_onTertiary = Color(0xFF00390B)
val md_theme_dark_tertiaryContainer = Color(0xFF005314)
val md_theme_dark_onTertiaryContainer = Color(0xFF93FA90)
val md_theme_dark_error = Color(0xFFFFB3AF)
val md_theme_dark_onError = Color(0xFF68000E)
val md_theme_dark_errorContainer = Color(0xFF900C1B)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD7)
val md_theme_dark_outline = Color(0xFF8B9297)
val md_theme_dark_background = Color(0xFF0F0F0F)
val md_theme_dark_onBackground = Color(0xFFE1E3E3)
val md_theme_dark_surface = Color(0xFF242424)
val md_theme_dark_onSurface = Color(0xFFC4C7C7)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C7CD)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E3)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inversePrimary = Color(0xff8a6e00)
val md_theme_dark_surfaceTint = Color(0xFF242424)
val md_theme_dark_outlineVariant = Color(0xFF41484D)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFFFAD86A)
